'use client'
import { ArrowRight, Check, Scale, Users, FileCheck, ShieldCheck, Clock, MapPin, ChevronDown, MessageCircle, Menu, X } from 'lucide-react'
import { useState, useEffect } from 'react'

const services=[['Residencia Temporal','Ideal para comenzar tu nueva vida. Vigencia de 2 años y proceso simple.'],['Residencia Permanente','Estabilidad para ti y tu familia, con todos los beneficios de vivir en Paraguay.'],['Cédula de Identidad','Gestionamos tu documento paraguayo de principio a fin, sin vueltas.']]
const steps=[['01','Evaluamos tu caso','Analizamos tu situación y te damos una ruta clara, sin costo.'],['02','Preparamos tus documentos','Nos ocupamos de la burocracia y revisamos cada detalle.'],['03','Presentamos el trámite','Acompañamiento presencial ante Migraciones hasta la aprobación.'],['04','Recibes tu cédula','Celebra tu nueva etapa con tu documentación en mano.']]
export default function Home(){const [open,setOpen]=useState(false); const [hero,setHero]=useState(0); const heroImages=['/images/fondo1.webp','/images/fondo2.webp','/images/fondo3.png','/videos/bienvenida.mp4']; useEffect(()=>{const t=setInterval(()=>setHero(v=>(v+1)%heroImages.length),5000); return()=>clearInterval(t)},[]); return <main>
<header className="nav"><a className="brand" href="#inicio"><span className="brand-mark">✦</span><span><b>Integración</b><small>Gestión de Residencia para Extranjeros</small></span></a><button className="nav-toggle" onClick={()=>setOpen(!open)} aria-label="Abrir menú">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}><a href="#inicio" onClick={()=>setOpen(false)}>Inicio</a><a href="#sobre" onClick={()=>setOpen(false)}>Sobre Mí</a><a href="#servicios" onClick={()=>setOpen(false)}>Servicios</a><a href="#cedula" onClick={()=>setOpen(false)}>Cédula Extranjera</a><a className="nav-cta" href="#contacto" onClick={()=>setOpen(false)}>Contactar</a><select className="lang" aria-label="Idioma"><option>ES</option><option>EN</option><option>PT</option></select></nav></header>
<section id="inicio" className="hero"><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow">Vivir en Paraguay · Living in Paraguay · Morar no Paraguai</p><h1>Tu Residencia en Paraguay.<br/><em>Es hora de hacerlo oficial.</em></h1><p className="lead">Obtén tu Residencia Paraguaya y tu Cédula de Identidad de forma rápida y segura.<br/>Nosotros nos encargamos de toda la burocracia ante Migraciones mientras tú<br/>disfrutas del país.</p><div className="trust"><span><Scale/> Asesoría Legal Profesional</span><span><Users/> Acompañamiento 100% personalizado</span></div><a className="primary" href="#contacto">Iniciar mi Trámite Hoy <ArrowRight size={20}/></a><p className="free"><Check size={18}/> Evaluación de tu caso 100% gratuita</p></div></section>
<section id="sobre" className="intro"><div><p className="eyebrow dark">TU NUEVA VIDA COMIENZA AQUÍ</p><h2>Paraguay te abre las puertas.</h2><p>Somos especialistas en movilidad internacional y residencia paraguaya. Te acompañamos con claridad, cercanía y experiencia para que instalarte en el país sea una experiencia tranquila.</p><a className="text-link" href="#contacto">Conoce cómo podemos ayudarte <ArrowRight size={17}/></a></div><div className="stats"><div><strong>+500</strong><span>familias acompañadas</span></div><div><strong>98%</strong><span>casos aprobados</span></div><div><strong>10+</strong><span>años de experiencia</span></div></div></section>
<section id="servicios" className="services"><p className="eyebrow dark center">SOLUCIONES A TU MEDIDA</p><h2 className="center">Todo lo que necesitas, en un solo lugar.</h2><div className="cards">{services.map(([t,d],i)=><article className="card" key={t}><div className="icon">{i===0?<FileCheck/>:i===1?<ShieldCheck/>:<Clock/>}</div><h3>{t}</h3><p>{d}</p><a href="#contacto">Saber más <ArrowRight size={16}/></a></article>)}</div></section>
<section className="process"><div className="process-head"><p className="eyebrow">SIMPLE, CLARO Y SEGURO</p><h2>Tu trámite, paso a paso.</h2><p>Te mantenemos informado en cada etapa, sin tecnicismos ni sorpresas.</p></div><div className="steps">{steps.map(([n,t,d])=><div className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section id="cedula" className="family"><div><p className="eyebrow dark">HECHO PARA EXTRANJEROS</p><h2>Tu tranquilidad es nuestra prioridad.</h2><p>Desde la primera consulta hasta que tengas tu cédula en mano, estamos a tu lado. Atención en español, inglés y portugués.</p><div className="checks"><span><Check/> Atención personalizada</span><span><Check/> Documentación transparente</span><span><Check/> Sin costos ocultos</span></div><a className="primary" href="#contacto">Hablar con un asesor <ArrowRight size={19}/></a></div><div className="family-card"><MapPin size={28}/><b>Asunción, Paraguay</b><span>Tu próximo hogar te espera</span></div></section>
<section className="testimonials"><p className="eyebrow dark center">HISTORIAS REALES</p><h2 className="center">Ellos ya lo hicieron oficial.</h2><div className="quotes"><blockquote>“El equipo de Integración hizo todo muy fácil. En pocas semanas ya tenía mi residencia y cédula.”<footer>— Marcos R., Brasil</footer></blockquote><blockquote>“La atención fue cercana y profesional desde el primer día. Los recomiendo totalmente.”<footer>— Sophie M., Francia</footer></blockquote></div></section>
<section className="faq"><p className="eyebrow dark center">PREGUNTAS FRECUENTES</p><h2 className="center">¿Tienes dudas?</h2>{['¿Cuánto demora el trámite de residencia?','¿Qué documentos necesito para comenzar?','¿Puedo incluir a mi familia en el proceso?'].map(q=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>Evaluamos tu caso sin costo y te indicamos los requisitos exactos según tu nacionalidad y situación.</p></details>)}</section>
<section id="contacto" className="contact"><div><p className="eyebrow">DA EL PRIMER PASO</p><h2>¿Listo para hacer<br/><em>tu residencia oficial?</em></h2><p>Cuéntanos tu situación. La primera evaluación es completamente gratuita.</p></div><form><input placeholder="Tu nombre"/><input placeholder="Tu email" type="email"/><input placeholder="WhatsApp"/><textarea placeholder="¿En qué podemos ayudarte?" rows={3}/><button className="primary" type="button">Solicitar evaluación gratuita <ArrowRight size={18}/></button></form></section>
<footer className="footer"><span>© 2024 Integración Paraguay</span><span>Residencia · Cédula · Asesoría Legal</span></footer><a className="whatsapp" href="https://wa.me/595981000000"><MessageCircle size={27}/></a>
</main>}
